### ISSUE TITLE
New UI mockup

### ISSUE THREAD

**Issue by fpesari** [Stazed/rakarrack-plus#23] opened 2021-02-06 19:03 UTC
Hello,

I am no graphic designer but I've used a fair share of plugins so I tried my hand at an alternative UI. Here is the result so far:

### New (FLTK theme, no effects yet)
![image](https://user-images.githubusercontent.com/52702101/107127374-f42ea900-68b5-11eb-9868-0e3e388c7d52.png)

### Original (FLTK theme)
![image](https://user-images.githubusercontent.com/52702101/107124224-cb50e880-68a2-11eb-8bae-24112b58582c.png)

This was all done using standard FLTK in `fluid` (and some `sed`). I think it is no masterpiece but I think it looks a bit less dated than the original rakarrack UI, since it is flatter.

I can't get the combo boxes not to show borders, though.

What do you think about it (keeping in mind that I am not a designer)? Sadly, I can't easily deploy it due to #22 - sorry but I am no FLTK expert!

**Comment by Stazed** [comment] 2021-02-07 01:45
I like the darker colors. I was able to achieve a similar look by simply changing the background colors, buttons, and leds. Perhaps, that is a simpler approach. If you find a look you like, then send me the "skin", File/Save Skin.
btw, the F1 help for Rakarrack-plus is extensive and mostly complete and up to date. A rarity for open source projects, sadly. Thanks to the original developers! 

Regarding any significant changes, be they gui or other, I am currently putting a hold on everything other than bug fixes and minor, trivial changes. To explain, I just spent the last two months re-factoring the main audio processing and preset/bank loading. This was an extensive undertaking that was necessary to fix embedded issues that were the demise of the original Rakarrack. Without these fixes, the project simply could not be maintained by me, and based on its demise, by anyone else. Though the worst is behind, there is still much that needs to be done to make this a long-term manageable project.  Until I finish cleaning things up, making enhancements, etc will only compound the problem making the cleanup worse. I realize from a user perspective, it appears that little is happening since the only way you could tell that something is being done is if a regression is introduced. This cleanup will likely take several more months. Patience!

**Comment by fpesari** [comment] 2021-02-07 09:47
What you are doing is great! I don't think you are doing little work and am very thankful and appreciative of what is being done :smiley_cat:

That said, I'd like to contribute to the project because I love rakarrack, it has given me a lot over the years, and I think one of the things which makes people dismiss it is the UI/UX. That's why I decided to focus on it; I also am no audio programming expert so I think someone more experienced than me can do better work in that regard.

I attach the `rakarrack.fl` file I made yesterday here (I had to rename it to `rakarrack.txt` for Github to accept the attachment), of course under the same terms of license as rakarrak-plus. Even though I am no designer, I am rather satisfied with the result and hope it could be a starting point for a more modern look.

I understand though that doing work on the GUI right now could be problematic. I've noticed, for example, that many GUI components have Spanish (I believe) names. I'd still like to go ahead and do all components in this style, if you don't mind. Then you can always reject the PR, but I'm curious to see how this would turn out in the end. What about it?

[rakarrack.txt](https://github.com/Stazed/rakarrack-plus/files/5938617/rakarrack.txt)

**Comment by Stazed** [comment] 2021-02-08 01:43
As I previously stated, I'm doing cleanup that will touch virtually everything. There is no point in sending me a PR on this at this time. I'm closing this, remind me again in a year....

**Closed by Stazed** 2021-02-08 01:43 UTC
